In [1]:
# 셀 1
import pandas as pd
import numpy as np

In [2]:
# 셀 2: 데이터 경로 설정 및 파일 불러오기
train_a_path = './data/train/A.csv'
train_b_path = './data/train/B.csv'
train_labels_path = './data/train.csv'

train_a = pd.read_csv(train_a_path)
train_b = pd.read_csv(train_b_path)
train_labels = pd.read_csv(train_labels_path)

In [3]:
# 셀 3: 데이터 병합
# train/A.csv와 train/B.csv를 상하로 연결
train_features = pd.concat([train_a, train_b])

# feature 데이터와 label 데이터를 'Test_id' 기준으로 병합
train_df = pd.merge(train_features, train_labels, on='Test_id')

In [4]:
# 셀 4: 병합된 학습 데이터 확인
print("--- 최종 학습 데이터 정보 ---")
train_df.info()

print("\n\n--- 데이터 샘플 (상위 5개) ---")
display(train_df.head())

--- 최종 학습 데이터 정보 ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 944767 entries, 0 to 944766
Data columns (total 65 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Test_id     944767 non-null  object
 1   Test_x      944767 non-null  object
 2   PrimaryKey  944767 non-null  object
 3   Age         944767 non-null  object
 4   TestDate    944767 non-null  int64
 5   A1-1        647241 non-null  object
 6   A1-2        647241 non-null  object
 7   A1-3        647241 non-null  object
 8   A1-4        647241 non-null  object
 9   A2-1        647240 non-null  object
 10  A2-2        647240 non-null  object
 11  A2-3        647240 non-null  object
 12  A2-4        647240 non-null  object
 13  A3-1        647240 non-null  object
 14  A3-2        647240 non-null  object
 15  A3-3        647240 non-null  object
 16  A3-4        647240 non-null  object
 17  A3-5        647240 non-null  object
 18  A3-6        647240 non-null  object
 19  A3-7        647240 non-null  object
 20  A4-1        647241 non-null  object
 21  A4-2        647241 non-null  object
 22  A4-3        647241 non-null  object
 23  A4-4        647241 non-null  object
 24  A4-5        647241 non-null  object
 25  A5-1        647239 non-null  object
 26  A5-2        647239 non-null  object
 27  A5-3        647239 non-null  object
 28  A6-1        647241 non-null  float64
 29  A7-1        647241 non-null  float64
 30  A8-1        647241 non-null  float64
 31  A8-2        647241 non-null  float64
 32  A9-1        647241 non-null  float64
 33  A9-2        647241 non-null  float64
 34  A9-3        647241 non-null  float64
 35  A9-4        647241 non-null  float64
 36  A9-5        647241 non-null  float64
 37  B1-1        297517 non-null  object
 38  B1-2        297517 non-null  object
 39  B1-3        297517 non-null  object
 40  B2-1        297523 non-null  object
 41  B2-2        297523 non-null  object
 42  B2-3        297523 non-null  object
 43  B3-1        297523 non-null  object
 44  B3-2        297523 non-null  object
 45  B4-1        297523 non-null  object
 46  B4-2        297523 non-null  object
 47  B5-1        297523 non-null  object
 48  B5-2        297523 non-null  object
 49  B6          297523 non-null  object
 50  B7          297524 non-null  object
 51  B8          297525 non-null  object
 52  B9-1        297526 non-null  float64
 53  B9-2        297526 non-null  float64
 54  B9-3        297526 non-null  float64
 55  B9-4        297526 non-null  float64
 56  B9-5        297526 non-null  float64
 57  B10-1       297526 non-null  float64
 58  B10-2       297526 non-null  float64
 59  B10-3       297526 non-null  float64
 60  B10-4       297526 non-null  float64
 61  B10-5       297526 non-null  float64
 62  B10-6       297526 non-null  float64
 63  Test_y      944767 non-null  object
 64  Label       944767 non-null  int64
dtypes: float64(20), int64(2), object(43)
memory usage: 468.5+ MB


--- 데이터 샘플 (상위 5개) ---

,Test_id,Test_x,PrimaryKey,Age,TestDate,A1-1,A1-2,A1-3,A1-4,A2-1,...,B9-4,B9-5,B10-1,B10-2,B10-3,B10-4,B10-5,B10-6,Test_y,Label
0,0x744773A3B58E27F1811B47B53331F272AB5E569A9F72...,A,0x744773A3B58E27F1811B47B53331F272AB5E569A9F72...,20a,201811,"2,2,1,2,1,2,1,1,2,1,2,1,1,2,1,2,2,1","1,3,3,2,3,3,2,2,3,3,2,1,2,1,1,1,2,1","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","29,33,56,64,5,-51,44,-1,0,31,30,5,67,33,43,21,...","1,1,2,3,1,2,2,3,3,1,1,3,2,2,1,2,3,3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,0
1,0xDA7DE599194F2B4F9624ACBCE96E66E2F8B357A4DD97...,A,0xDA7DE599194F2B4F9624ACBCE96E66E2F8B357A4DD97...,20a,201811,"2,2,1,2,2,1,1,1,2,2,1,2,1,1,2,1,2,1","3,2,2,1,1,3,1,1,2,3,2,1,3,1,2,3,3,2","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","76,1,27,25,41,34,-24,7,18,85,-18,-21,31,-7,18,...","2,3,3,1,2,2,3,2,3,1,2,3,1,3,2,1,1,1",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,0
2,0x7DF700D37380AD164ADF79B485C3A84A571186E3DB27...,A,0x7DF700D37380AD164ADF79B485C3A84A571186E3DB27...,20a,201802,"1,1,2,1,2,2,2,2,1,2,1,1,1,1,1,2,2,2","2,3,3,1,1,2,1,1,3,2,1,2,2,3,1,2,3,3","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","-1,22,0,-37,-21,7,-34,-21,-79,-26,-80,-23,-63,...","1,1,3,2,3,2,1,1,1,1,3,2,2,2,2,3,3,3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,0
3,0xAB057D1B8C3A8FB6E99F1B6E0F95086150951BCA8630...,A,0xAB057D1B8C3A8FB6E99F1B6E0F95086150951BCA8630...,20a,201805,"2,2,2,2,1,2,1,1,2,2,1,1,1,1,2,1,2,1","1,3,3,1,2,2,2,3,2,3,2,1,1,1,2,3,1,3","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","-60,25,-25,-34,-40,-60,-46,-79,-77,-51,-80,-62...","1,2,2,3,1,1,2,2,3,1,3,2,1,3,3,3,2,1",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,0
4,0xAD4EC2C13080BC51C988805376AB404CCD2BA53CB108...,A,0xAD4EC2C13080BC51C988805376AB404CCD2BA53CB108...,20a,201806,"2,2,1,1,2,1,1,2,1,1,1,1,2,2,1,2,2,2","1,3,1,3,2,1,1,1,3,2,2,2,2,3,3,3,2,1","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0","-42,-77,-33,-3,-38,-58,-88,-4,-28,-58,-40,-29,...","1,3,3,2,2,2,3,1,3,1,1,2,1,3,1,2,3,2",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,0

In [5]:
# 셀 5: 데이터 경로 설정 및 파일 불러오기
test_a_path = './data/test/A.csv'
test_b_path = './data/test/B.csv'
test_info_path = './data/test.csv'

test_a = pd.read_csv(test_a_path)
test_b = pd.read_csv(test_b_path)
test_info = pd.read_csv(test_info_path)

In [6]:
# 셀 6: 데이터 병합
# test/A.csv와 test/B.csv를 상하로 연결
test_features = pd.concat([test_a, test_b])

# feature 데이터와 test.csv의 정보를 'Test_id' 기준으로 병합
test_df = pd.merge(test_features, test_info, on='Test_id')

In [7]:
# 셀 7: 병합된 테스트 데이터 확인
print("--- 최종 테스트 데이터 정보 ---")
test_df.info()

print("\n\n--- 데이터 샘플 (상위 5개) ---")
display(test_df.head())

--- 최종 테스트 데이터 정보 ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 64 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Test_id     10 non-null     object
 1   Test_x      10 non-null     object
 2   PrimaryKey  10 non-null     object
 3   Age         10 non-null     object
 4   TestDate    10 non-null     int64
 5   A1-1        4 non-null      object
 6   A1-2        4 non-null      object
 7   A1-3        4 non-null      object
 8   A1-4        4 non-null      object
 9   A2-1        4 non-null      object
 10  A2-2        4 non-null      object
 11  A2-3        4 non-null      object
 12  A2-4        4 non-null      object
 13  A3-1        4 non-null      object
 14  A3-2        4 non-null      object
 15  A3-3        4 non-null      object
 16  A3-4        4 non-null      object
 17  A3-5        4 non-null      object
 18  A3-6        4 non-null      object
 19  A3-7        4 non-null      object
 20  A4-1        4 non-null      object
 21  A4-2        4 non-null      object
 22  A4-3        4 non-null      object
 23  A4-4        4 non-null      object
 24  A4-5        4 non-null      object
 25  A5-1        4 non-null      object
 26  A5-2        4 non-null      object
 27  A5-3        4 non-null      object
 28  A6-1        4 non-null      float64
 29  A7-1        4 non-null      float64
 30  A8-1        4 non-null      float64
 31  A8-2        4 non-null      float64
 32  A9-1        4 non-null      float64
 33  A9-2        4 non-null      float64
 34  A9-3        4 non-null      float64
 35  A9-4        4 non-null      float64
 36  A9-5        4 non-null      float64
 37  B1-1        6 non-null      object
 38  B1-2        6 non-null      object
 39  B1-3        6 non-null      object
 40  B2-1        6 non-null      object
 41  B2-2        6 non-null      object
 42  B2-3        6 non-null      object
 43  B3-1        6 non-null      object
 44  B3-2        6 non-null      object
 45  B4-1        6 non-null      object
 46  B4-2        6 non-null      object
 47  B5-1        6 non-null      object
 48  B5-2        6 non-null      object
 49  B6          6 non-null      object
 50  B7          6 non-null      object
 51  B8          6 non-null      object
 52  B9-1        6 non-null      float64
 53  B9-2        6 non-null      float64
 54  B9-3        6 non-null      float64
 55  B9-4        6 non-null      float64
 56  B9-5        6 non-null      float64
 57  B10-1       6 non-null      float64
 58  B10-2       6 non-null      float64
 59  B10-3       6 non-null      float64
 60  B10-4       6 non-null      float64
 61  B10-5       6 non-null      float64
 62  B10-6       6 non-null      float64
 63  Test_y      10 non-null     object
dtypes: float64(20), int64(1), object(43)
memory usage: 5.1+ KB


--- 데이터 샘플 (상위 5개) ---

,Test_id,Test_x,PrimaryKey,Age,TestDate,A1-1,A1-2,A1-3,A1-4,A2-1,...,B9-3,B9-4,B9-5,B10-1,B10-2,B10-3,B10-4,B10-5,B10-6,Test_y
0,0x6AAEB8D4B2C1142AB4C1282DA2430697EB919590B134...,A,0x6AAEB8D4B2C1142AB4C1282DA2430697EB919590B134...,40b,202301,"2,1,2,1,2,1,1,1,1,2,2,1,1,1,2,2,2,2","1,3,1,1,2,2,2,3,1,3,1,3,1,2,2,3,2,3","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","4,13,25,82,24,55,4,-37,26,-8,12,73,78,55,58,16...","1,1,2,3,2,1,3,3,2,3,1,3,2,1,1,2,2,3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
1,0xDFF236F959D1FF9710399CA54504269A2258B1442186...,A,0xDFF236F959D1FF9710399CA54504269A2258B1442186...,60a,202301,"2,1,1,2,2,1,2,1,1,1,1,1,2,2,1,2,2,2","3,3,1,1,3,3,2,3,2,1,2,1,1,1,2,2,3,2","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","8,14,-12,-12,8,-29,-32,30,-18,56,32,18,-42,0,-...","1,1,1,2,2,3,1,3,1,3,2,3,2,2,3,2,3,1",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,0x2A862811BC15845ECE4281E6F76483FA02AE6B73057C...,A,0x2A862811BC15845ECE4281E6F76483FA02AE6B73057C...,60a,202307,"2,2,1,2,1,2,2,2,2,1,1,1,1,2,1,1,1,2","3,1,2,1,3,3,1,2,2,2,3,2,3,2,1,1,1,3","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","16,38,27,-4,22,-25,127,52,115,101,-79,61,99,87...","1,2,2,3,3,2,3,1,2,3,2,1,1,2,1,3,3,1",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
3,0x0844ED886E9D16C368D0623490674F9B35E14FE4F929...,A,0x0844ED886E9D16C368D0623490674F9B35E14FE4F929...,60b,202302,"2,2,2,2,2,1,1,1,1,2,2,2,1,1,2,1,1,1","2,3,1,2,3,3,3,3,2,1,3,2,1,2,1,2,1,1","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","1,136,-51,64,85,48,133,133,44,16,85,7,1,61,-60...","3,3,2,3,1,1,3,2,3,1,2,1,2,3,2,2,1,1",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
4,0xF63480EE11C5B9CDF481941E4654C5C0F706F2A9DA46...,B,0xF63480EE11C5B9CDF481941E4654C5C0F706F2A9DA46...,70a,202303,NaN,NaN,NaN,NaN,NaN,...,0.0,35.0,0.0,20.0,0.0,0.0,60.0,5.0,20.0,B

In [8]:
# 셀 8: 병합된 학습 데이터(train_df)를 CSV 파일로 저장
# 파일은 data 폴더 안에 train_merged.csv 라는 이름으로 저장됩니다.
train_df.to_csv('./data/train_merged.csv', index=False, encoding='utf-8-sig')

print("✅ './data/train_merged.csv' 파일 저장 완료!")

✅ './data/train_merged.csv' 파일 저장 완료!

In [9]:
# 셀 9: 병합된 테스트 데이터(test_df)를 CSV 파일로 저장
# 파일은 data 폴더 안에 test_merged.csv 라는 이름으로 저장됩니다.
test_df.to_csv('./data/test_merged.csv', index=False, encoding='utf-8-sig')

print("✅ './data/test_merged.csv' 파일 저장 완료!")

✅ './data/test_merged.csv' 파일 저장 완료!